//Cada dia será armazenado em uma posição de um array em forma de objeto.
/*
    O objeto será composto por:
        -Título
        -Conteúdo
        -Dia
        -Mês
        -bom   "Esse parâmetro apresentará um valor entre 0 e 2 que dirá se o dia foi bom, médio, ou ruim"
*/


let dias = [{"id":1,"titulo":"Dia de conhecer a bisa...","conteudo":"Levei presentes pra Nina depois da psicóloga dela. Ela me convidou para subir e conhecer a bisavó.","dia":15,"mes":7,"bom":2},{"id":2,"titulo":null,"conteudo":null,"dia":16,"mes":7,"bom":1},{"id":3,"titulo":null,"conteudo":null,"dia":17,"mes":7,"bom":1},{"id":4,"titulo":null,"conteudo":null,"dia":18,"mes":7,"bom":1},{"id":5,"titulo":null,"conteudo":null,"dia":19,"mes":7,"bom":1},{"id":6,"titulo":null,"conteudo":null,"dia":20,"mes":7,"bom":1},{"id":7,"titulo":null,"conteudo":null,"dia":21,"mes":7,"bom":1},{"id":8,"titulo":null,"conteudo":null,"dia":22,"mes":7,"bom":1},{"id":9,"titulo":null,"conteudo":null,"dia":23,"mes":7,"bom":1},{"id":10,"titulo":null,"conteudo":null,"dia":24,"mes":7,"bom":1},{"id":11,"titulo":null,"conteudo":null,"dia":25,"mes":7,"bom":1},{"id":12,"titulo":null,"conteudo":null,"dia":26,"mes":7,"bom":1},{"id":13,"titulo":null,"conteudo":null,"dia":27,"mes":7,"bom":1},{"id":14,"titulo":null,"conteudo":null,"dia":28,"mes":7,"bom":1},{"id":15,"titulo":null,"conteudo":null,"dia":29,"mes":7,"bom":1},{"id":16,"titulo":null,"conteudo":null,"dia":30,"mes":7,"bom":1},{"id":17,"titulo":null,"conteudo":null,"dia":31,"mes":7,"bom":1},{"id":18,"titulo":null,"conteudo":null,"dia":1,"mes":8,"bom":1},{"id":19,"titulo":null,"conteudo":null,"dia":2,"mes":8,"bom":1},{"id":20,"titulo":null,"conteudo":null,"dia":3,"mes":8,"bom":1},{"id":21,"titulo":null,"conteudo":null,"dia":4,"mes":8,"bom":1},{"id":22,"titulo":null,"conteudo":null,"dia":5,"mes":8,"bom":1},{"id":23,"titulo":null,"conteudo":null,"dia":6,"mes":8,"bom":1},{"id":24,"titulo":null,"conteudo":null,"dia":7,"mes":8,"bom":1},{"id":25,"titulo":null,"conteudo":null,"dia":8,"mes":8,"bom":1},{"id":26,"titulo":null,"conteudo":null,"dia":9,"mes":8,"bom":1},{"id":27,"titulo":null,"conteudo":null,"dia":10,"mes":8,"bom":1},{"id":28,"titulo":null,"conteudo":null,"dia":11,"mes":8,"bom":1},{"id":29,"titulo":null,"conteudo":null,"dia":12,"mes":8,"bom":1},{"id":30,"titulo":null,"conteudo":null,"dia":13,"mes":8,"bom":1},{"id":31,"titulo":null,"conteudo":null,"dia":14,"mes":8,"bom":1}]